version: "3.8"
services:
  app:
    container_name: nestjs-study
    build:
      context: .
      dockerfile: dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=dev
    env_file:
      - .env.dev
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres
      - ./init-data.sh:/docker-entrypoint-initdb.d/init-data.sh
    environment:
      - POSTGRES_PASSWORD=postgres
    env_file:
      - .env.dev

volumes:
  app:
    driver: local
  postgres:
    driver: local
